### ISSUE TITLE
Tray Icon Extra Infos

### ISSUE THREAD

**Issue by samytichadou** [dryad-naiad-software/sethlans#1]
Hi, i thought it would be great to have some extra infos about local node (or server) on the tray icon.

For example, color code to show you in a glance if you are rendering or not, perhaps even on right click menu additional command like "enable/disable node" or direct link to node page.

Thanks for this tool

**Comment by marioestrella** [comment]
Added some of the improvements mentioned.  I did take a look at CGRU, disabling and enabling a node on the node itself would require some new API changes.  Shutting down Sethlans on the node is usually enough to have the system reassign the queue item to another node so for now that's a good work around if you don't have access to the server.

**Comment by marioestrella** [comment]
Beta 2 scheduled for the 12th of April will have the new icon changing ability as well as the improved menu.
